name: CI/CD
on:
  push:
    tags:
      - "*"
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Installing Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Run tests
        run: cargo test --verbose

  release-windows:
    name: Release Windows
    if: startsWith(github.ref, 'refs/tags/windows')
    needs: test
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Installing Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: cargo build --release --verbose

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: .\target\release\tic-tac-toe.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-linux:
    name: Release Linux
    if: startsWith(github.ref, 'refs/tags/linux')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Installing Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: cargo build --release --verbose

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/release/tic-tac-toe.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
